services:
  node:
    user: root
    image: node
    container_name: node
    entrypoint: tail -f /dev/null
    working_dir: /cruds
    volumes:
      - ./cruds:/cruds
    network_mode: host


  redis:
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

  mongodb:
    image: mongodb/mongodb-community-server
    volumes:
      - ./mongo:/data/db mongodb/
    networks:
      - default
    ports:
      - "27017:27017"

  cassandra:
    image: cassandra:latest
    volumes:
      - ./cassandra:/var/lib/cassandra
    networks:
      - default
    ports:
      - "9042:9042"
