services:
  redis:
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

  mongodb:
    image: mongodb/mongodb-community-server
    volumes:
      - ./mongo:/data/db mongodb/
    networks:
      - default
    ports:
      - "27017:27017"

  cassandra:
    image: cassandra
    volumes:
      - ./cassandra:/var/lib/cassandra
    networks:
      - default
    ports:
      - "9042:9042"
